version: '3'
services:
  #######################################
  # APPLICATION USERS SERVICE ENVIRONMENT
  #######################################
  users:
    build:
      context: ./docker
      dockerfile: Dockerfile.users
    restart: always
    ports:
      - 3000:3000
    env_file: ./services/users/.env
    volumes:
      - /usr/share/app/services/users
      - /usr/share/app/services/users/node_modules
    networks:
      - node-microservices
  #######################################
  # APPLICATION ROLES SERVICE ENVIRONMENT
  #######################################
  roles:
    build:
      context: ./docker
      dockerfile: Dockerfile.roles
    restart: always
    ports:
      - 3001:3001
    env_file: ./services/roles/.env
    volumes:
      - /usr/share/app/services/roles
      - /usr/share/app/services/roles/node_modules
    networks:
      - node-microservices
  #############################
  # PROXY SERVICES ENVIRONMENT
  #############################
  proxy:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - users
      - roles
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - node-microservices
#############################
# NETWORKS SHARING GROUP
#############################
networks:
  node-service: